# Generated by Django 3.0.5 on 2020-06-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200605_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_related_name': 'books', 'ordering': ['-created_date']},
        ),
    ]
