# Generated by Django 3.0.5 on 2020-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200605_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_related_name': 'events', 'ordering': ['-created_date']},
        ),
    ]
