# Generated by Django 3.0.5 on 2020-06-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200605_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_date']},
        ),
    ]
