# Generated by Django 3.0.5 on 2020-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200607_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no_photos', upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(default='null'),
        ),
    ]
