# Generated by Django 3.0.5 on 2020-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='release_date',
            field=models.DateField(),
        ),
    ]
